// import React from 'react'
// import styles from '../styles/Home.module.css'
// import Image from 'next/image'
// import { NextSeo } from 'next-seo';
// import Link from 'next/link';




// function about() {
//     return (
//         <div className={styles.container}>
//             <NextSeo
//                 title="PPGenerator | About Us"
//                 description="Privacy Policy generator used to generate policy pages for app and website"

//             />
//             <nav className={styles.mainnav}>
//                 <ul>
//                     <li><Link href="/">Home</Link></li>
//                     <li><Link href="/about">About</Link></li>
//                     <li><Link href="/privacy-policy">Policy</Link></li>
//                     <li><Link href="/contact">Contact</Link></li>
//                 </ul>
//             </nav>

//             <main className={styles.main}>

//                 <div className={styles.innerdiv}>


//                     <h2>Hello there,</h2>
//                     <p className={styles.para}>

//                         This web-app aims at making journey of bloggers and developers easy without being worried by privacy policy page. The privacy policy generated by this website might resemble with some other websites as well. But the whole point is that, at the end of the day it is just policy and it will certainly be same. Basically it fulfills all the requirements demanded by google. So don&apos;t worry it will be perfect.

//                         Also there is About Us and DMCA generaters as well. They are also preety much well designed and I have tried my best to make it as professional as i can.

//                         If you have any suggestions on how I can improve this web-app then do let me know.

//                         This web-app is made by santosh pant as a hobby project and anyone who wish to contribute to this website can contact him at <span className={styles.span}>iamsantoshpant@gmail.com </span>  or can get connected with him in social media by following link
//                     </p>

//                     <button className={styles.btn}>
//                         <a href="https://www.santoshpant.com.np/">
//                             Click Here
//                         </a>
//                     </button>
//                 </div>
//             </main>
//             <footer className={styles.footer}>
//                 <Link
//                     href="https://www.ppgenerator.com/"
//                     target="_blank"
//                     rel="noopener noreferrer"
//                 >
//                     Copyright @ ppgenerator 2022
//                     <span className={styles.logo}>
//                         <Image src="/logo.png" alt="ppgenerator logo" width={25} height={25} />
//                     </span>
//                 </Link>
//             </footer>
//         </div>
//     )
// }

// export default about;

import React from 'react'

const About = () => {
    return (
        <div>A</div>
    )
}

export default About