import React from 'react'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { NextSeo } from 'next-seo';
import Link from 'next/link';




const contact = () => {
    return (
        <div className={styles.container}>
            <NextSeo
                title="PPGenerator || Policy"
                description="Privacy Policy generator used to generate policy pages for app and website"

            />
            <nav className={styles.mainnav}>
                <ul>
                    <li><Link href="/">Home</Link></li>
                    <li><Link href="/about">About</Link></li>
                    <li><Link href="/privacy-policy">Policy</Link></li>
                    <li><Link href="/contact">Contact</Link></li>
                </ul>
            </nav>

            <main className={styles.main}>


                <div className={styles.innerdiv}>


                    <h1>Contact Us</h1>
                    <p>
                        This web-app aims at making journey of bloggers and developers easy without being worried by privacy policy page. The privacy policy generated by this website might resemble with some other websites as well. But the whole point is that, at the end of the day it is just policy and it will certainly be same. Basically it fulfills all the requirements demanded by google. So don&apos;t worry it will be perfect. </p>

                    <p>  If you have any issue with this web-app or for any business related purpose then you can reach out to me either on mail or on social medias as well. All the necessary details are below:</p>


                    <p>
                        Email:  iamsantoshpant@gmail.com  </p>



                    <p>   Website: santoshpant.com.np </p>





                </div>
                <button className={styles.btn}>
                    <a href="https://www.santoshpant.com.np/">
                        Contact Me
                    </a>
                </button>
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://www.ppgenerator.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Copyright @ ppgenerator 2022
                    <span className={styles.logo}>
                        <Image src="/logo.png" alt="ppgenerator logo" width={25} height={25} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default contact;

